name: ratesewa
region: sgp

services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: Prasan1/ratesewa

    build_command: pip install -r requirements.txt

    run_command: bash startup.sh

    http_port: 8080

    instance_count: 1
    instance_size_slug: basic-xxs

    routes:
      - path: /

    envs:
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: CHANGE_THIS_TO_GENERATED_SECRET_KEY

      - key: SESSION_COOKIE_SECURE
        scope: RUN_TIME
        value: "True"

      - key: DATABASE_URL
        scope: RUN_TIME
        value: "sqlite:///instance/doctors.db"
