name: ratesewa
region: sgp

services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: Prasan1/ratesewa

    build_command: pip install -r requirements.txt && mkdir -p instance && python3 -c "from app import app, db; app.app_context().push(); db.create_all(); print('✅ Database initialized')"

    run_command: gunicorn --worker-tmp-dir /dev/shm --workers 2 --bind 0.0.0.0:8080 app:app

    http_port: 8080

    instance_count: 1
    instance_size_slug: basic-xxs

    routes:
      - path: /

    envs:
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: CHANGE_THIS_TO_GENERATED_SECRET_KEY

      - key: SESSION_COOKIE_SECURE
        scope: RUN_TIME
        value: "True"

      - key: DATABASE_URL
        scope: RUN_TIME
        value: "sqlite:///instance/doctors.db"
